pipeline {
    agent { label 'java17' }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://gitlab.com/trn-kieen/loci.git',
                    credentialsId: 'jenkins'  // gitlab-token
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package -DskipTests'
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            updateGitlabCommitStatus name: 'jenkins-build', state: 'success'
        }
        failure {
            updateGitlabCommitStatus name: 'jenkins-build', state: 'failed'
        }
    }
  // stage('Docker build & push') {
  //   steps {
  //     script {
  //       def shortCommit = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
  //       def image = "your-dockerhub/loci-backend:${shortCommit}"
  //       docker.withRegistry('https://registry.hub.docker.com', 'docker-registry-credentials') {
  //         def app = docker.build("${image}", "./backend")
  //         app.push()
  //         app.push("latest")
  //       }
  //     }
  //   }
  // }
}
