pipeline {
    agent { label 'node18' }

    environment {
        NODE_OPTIONS = '--max_old_space_size=4096'  // avoid OOM on big apps
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        timeout(time: 10, unit:MINUTES)
    }

  stages {
      stage('Checkout') {
          steps {
              checkout scm  // re-uses webhook ref
          }
      }
  stage('Install dependencies') {
    steps {
      dir('frontend') {
        sh 'npm ci'
      }
    }
  }

  stage('Lint') {
    steps {
      dir('frontend') {
        sh 'npm run lint'
      }
    }
  }

  // TODO: add chrome for karma unit test
  // stage('Unit Test') {
  //   steps {
  //     dir('frontend') {
  //       // sh 'npm run test:ci'
  //       sh 'npm run test'
  //     }
  //   }
  //   post {
  //     always {
  //       publishHTML([
  //         allowMissing: false,
  //         alwaysLinkToLastBuild: true,
  //         keepAll: true,
  //         reportDir: 'loci-frontend/coverage',
  //         reportFiles: 'index.html',
  //         reportName: 'Coverage Report'
  //       ])
  //     }
  //   }
  // }

  stage('Build') {
    steps {
      dir('frontend') {
        sh 'npm run build'       // angular.json
        // or force prod:  sh 'npm run build -- --configuration=production'
      }
    }
  }
 stage('Docker build & push') {
  steps {
    script {
      def shortCommit = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
      def image = "your-dockerhub/loci-frontend:${shortCommit}"
      docker.withRegistry('https://registry.hub.docker.com', 'docker-registry-credentials') {
        def app = docker.build("${image}", "./loci")
        app.push()
        app.push("latest")
      }
    }
  }
}

    post {
        success {
            updateGitlabCommitStatus name: 'jenkins-frontend', state: 'success'
        }
        failure {
            updateGitlabCommitStatus name: 'jenkins-frontend', state: 'failed'
        }
    }
}
}
